title: Fastpca
description: Fast, parallelized implementation of Principal Component Analysis with constant memory consumption for large data sets.
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
